site_name: Sostenibilidad Aplicada al Sistema Productivo

nav:
  - Home: index.md
  # - Unidad 1. - La Sostenibilidad: unidad1/unidad1.md
  # - Unidad 2. - Los retos sociambientales actuales: unidad2/unidad2.md

theme:
  name: material
  features:
    - content.code.copy
    - content.tabs.link
  navigation_depth: 3
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode (predeterminado)
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode (predeterminado)
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to automatic mode

extra_css:
  - "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
  - css/custom.css
  - css/extra.css  # Deja este CSS para posibles ajustes adicionales

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji
  - pymdownx.arithmatex
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.smartsymbols
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tasklist
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.progressbar
  - pymdownx.tabbed
  - toc:
      toc_depth: 3
